---
apiVersion: v1
kind: ConfigMap

metadata:
    name: api-common

data:
    FLASK_PORT: "8281"
    FLASK_APP: sweetrpg_library_api.application.main:create_app
    FLASK_ENV: production
    NEW_RELIC_CONFIG_FILE: /config/newrelic.ini
